<%@ include file="../fragments/tags.jspf" %>
<%@ include file="../fragments/header.jspf" %>
<section class="card"><h2><c:out value="${purchase.number}"/> <span class="badge"><c:out value="${purchase.status}"/></span></h2>
  <dl><dt>仕入先</dt><dd><a href="<c:out value='${ctx}'/>/suppliers.do?op=detail&amp;id=<c:out value='${purchase.supplier.id}'/>"><c:out value="${purchase.supplierName}"/></a></dd><dt>入荷倉庫</dt><dd><c:out value="${purchase.warehouse.name}"/></dd><dt>発注日 / 入荷予定日</dt><dd><fmt:formatDate value="${purchase.orderDate}" pattern="yyyy-MM-dd"/> / <fmt:formatDate value="${purchase.expectedDate}" pattern="yyyy-MM-dd"/></dd><dt>税抜発注額</dt><dd><fmt:formatNumber value="${purchase.totalAmount}" pattern="#,##0.00"/> 円</dd><dt>発注条件</dt><dd class="prewrap"><c:out value="${purchase.orderingInstructions}"/></dd><dt>備考</dt><dd class="prewrap"><c:out value="${purchase.notes}"/></dd><dt>起票 / 申請 / 承認</dt><dd><c:out value="${purchase.createdBy}"/> / <c:out value="${purchase.submittedBy}"/> / <c:out value="${purchase.approvedBy}"/></dd><dt>差戻し・取消・打切り理由</dt><dd><c:out value="${purchase.decisionReason}"/></dd></dl>
</section>
<section class="card"><h2>発注明細</h2><div class="table-wrap"><table><thead><tr><th>商品 / 仕入先商品コード</th><th>予定日</th><th class="number">発注 / 良品 / 不良 / 打切</th><th class="number">残数</th><th>入数 / 納期</th><th class="number">単価 / 金額</th></tr></thead><tbody>
  <c:forEach items="${purchase.lines}" var="line"><tr><td><c:out value="${line.productCode}"/> <c:out value="${line.productName}"/><br><c:out value="${line.supplierProductCode}"/><br><span class="muted"><c:out value="${line.notes}"/></span></td><td><fmt:formatDate value="${line.expectedDate}" pattern="yyyy-MM-dd"/></td><td class="number"><c:out value="${line.quantity}"/> / <c:out value="${line.receivedQuantity}"/> / <c:out value="${line.rejectedQuantity}"/> / <c:out value="${line.cancelledQuantity}"/></td><td class="number"><c:out value="${line.outstandingQuantity}"/></td><td><c:out value="${line.orderPackSize}"/> / <c:out value="${line.leadTimeDays}"/>日</td><td class="number"><fmt:formatNumber value="${line.unitCost}" pattern="#,##0.00"/><br><fmt:formatNumber value="${line.lineAmount}" pattern="#,##0.00"/></td></tr></c:forEach>
</tbody></table></div></section>
<section class="card"><h2>発注操作</h2><form action="<c:out value='${ctx}'/>/purchases.do" method="post"><%@ include file="../fragments/identity.jspf" %><label>差戻し・取消・残数打切り理由<textarea name="reason" maxlength="500"><c:out value="${form.reason}"/></textarea></label>
  <div class="actions"><c:if test="${(canWAREHOUSE or canMANAGER) and purchase.editable}"><a class="button" href="<c:out value='${ctx}'/>/purchases.do?op=edit&amp;id=<c:out value='${purchase.id}'/>">下書き編集</a><button name="op" value="submit" class="primary">承認申請</button></c:if>
    <c:if test="${canMANAGER and purchase.status eq 'SUBMITTED'}"><c:if test="${purchase.createdBy ne actor.login and purchase.submittedBy ne actor.login}"><button name="op" value="approve" class="primary">承認</button></c:if><button name="op" value="reject">差戻し</button></c:if>
    <c:if test="${(canWAREHOUSE or canMANAGER or canBATCH) and purchase.receivable}"><a class="button primary" href="<c:out value='${ctx}'/>/purchaseReceipts.do?op=new&amp;orderId=<c:out value='${purchase.id}'/>">入荷・検品を登録</a></c:if>
    <c:if test="${(canWAREHOUSE or canMANAGER) and (purchase.editable or purchase.status eq 'SUBMITTED' or (canMANAGER and purchase.status eq 'APPROVED'))}"><button name="op" value="cancel" class="danger">発注を取消</button></c:if>
    <c:if test="${canMANAGER and purchase.receivable}"><button name="op" value="close" class="danger">発注残数を打切り</button></c:if>
    <a class="button" href="<c:out value='${ctx}'/>/purchases.do">一覧へ</a>
  </div>
</form></section>
<section class="card"><h2>入荷・検品履歴</h2><div class="table-wrap"><table><thead><tr><th>入荷番号</th><th>入荷日 / 納品番号</th><th class="number">良品 / 不良</th><th>受領者</th></tr></thead><tbody>
  <c:forEach items="${receipts}" var="receipt"><tr><td><a href="<c:out value='${ctx}'/>/purchaseReceipts.do?op=detail&amp;id=<c:out value='${receipt.id}'/>"><c:out value="${receipt.number}"/></a></td><td><fmt:formatDate value="${receipt.receiptDate}" pattern="yyyy-MM-dd"/><br><c:out value="${receipt.supplierDeliveryNumber}"/></td><td class="number"><c:out value="${receipt.acceptedQuantity}"/> / <c:out value="${receipt.rejectedQuantity}"/></td><td><c:out value="${receipt.receivedBy}"/></td></tr></c:forEach><c:if test="${empty receipts}"><tr><td colspan="4" class="empty">入荷・検品履歴はありません。</td></tr></c:if>
</tbody></table></div></section>
<%@ include file="../fragments/footer.jspf" %>
