<%@ include file="../fragments/tags.jspf" %>
<%@ include file="../fragments/header.jspf" %>
<section class="card"><h2><c:out value="${supplier.code}"/> · <c:out value="${supplier.name}"/></h2>
  <dl><dt>利用 / 発注状態</dt><dd><c:out value="${supplier.active ? '利用中' : '停止中'}"/> / <c:out value="${supplier.onHold ? '保留' : '通常'}"/></dd><dt>住所 / 電話</dt><dd><c:out value="${supplier.postalCode}"/> <c:out value="${supplier.address}"/><br><c:out value="${supplier.telephone}"/></dd><dt>締日 / 支払サイト</dt><dd><c:out value="${supplier.closingDay eq 31 ? '末日' : supplier.closingDay}"/> / <c:out value="${supplier.paymentTermDays}"/>日</dd><dt>最低発注額 / 標準納期</dt><dd><fmt:formatNumber value="${supplier.minimumOrderAmount}" pattern="#,##0.00"/> 円 / <c:out value="${supplier.defaultLeadTimeDays}"/>日</dd><dt>発注条件</dt><dd class="prewrap"><c:out value="${supplier.orderingInstructions}"/></dd><dt>備考</dt><dd class="prewrap"><c:out value="${supplier.notes}"/></dd></dl>
  <div class="actions"><c:if test="${canMANAGER}"><a class="button primary" href="<c:out value='${ctx}'/>/suppliers.do?op=edit&amp;id=<c:out value='${supplier.id}'/>">仕入先を編集</a><a class="button" href="<c:out value='${ctx}'/>/supplierProducts.do?op=new&amp;supplierId=<c:out value='${supplier.id}'/>">調達条件を追加</a></c:if><c:if test="${canWAREHOUSE or canMANAGER}"><a class="button" href="<c:out value='${ctx}'/>/purchases.do?op=new&amp;supplierId=<c:out value='${supplier.id}'/>">この仕入先へ発注</a></c:if><a class="button" href="<c:out value='${ctx}'/>/suppliers.do">一覧へ</a></div>
</section>
<c:if test="${canBILLING}"><section class="card"><h2>過去の仕入取引の請求処理</h2><p class="help">停止中の仕入先でも、検収済みの過去取引は買掛請求として処理できます。仕入先ID：<span class="mono"><c:out value="${supplier.id}"/></span></p><div class="actions"><a class="button" href="<c:out value='${ctx}'/>/apInvoices.do?op=new&amp;supplierId=<c:out value='${supplier.id}'/>">この仕入先の請求を入力</a><a class="button" href="<c:out value='${ctx}'/>/apPayments.do?op=new&amp;supplierId=<c:out value='${supplier.id}'/>">この仕入先への支払</a></div></section></c:if>
<section class="card"><h2>商品別の調達条件</h2><p class="help">有効期間・数量段階から仕入単価が選ばれます。優先仕入先の設定は補充候補に利用します。</p>
  <div class="table-wrap"><table><thead><tr><th>商品 / 仕入先商品コード</th><th>適用期間</th><th>最低数量 / 入数 / 納期</th><th class="number">単価</th><th>状態 / 優先</th><th>操作</th></tr></thead><tbody>
    <c:forEach items="${supplierProducts}" var="item"><tr><td><c:out value="${item.product.code}"/> <c:out value="${item.product.name}"/><br><c:out value="${item.supplierProductCode}"/></td><td><fmt:formatDate value="${item.validFrom}" pattern="yyyy-MM-dd"/> ～<br><fmt:formatDate value="${item.validTo}" pattern="yyyy-MM-dd"/></td><td><c:out value="${item.minimumQuantity}"/> / <c:out value="${item.orderPackSize}"/> / <c:out value="${item.leadTimeDays}"/>日</td><td class="number"><fmt:formatNumber value="${item.unitCost}" pattern="#,##0.00"/></td><td><c:out value="${item.active ? '有効' : '無効'}"/> / <c:out value="${item.preferred ? '優先' : '通常'}"/></td><td><c:if test="${canMANAGER}"><a href="<c:out value='${ctx}'/>/supplierProducts.do?op=edit&amp;id=<c:out value='${item.id}'/>&amp;supplierId=<c:out value='${supplier.id}'/>">編集</a></c:if></td></tr></c:forEach>
    <c:if test="${empty supplierProducts}"><tr><td colspan="6" class="empty">調達条件がありません。発注する商品について契約条件を登録してください。</td></tr></c:if>
  </tbody></table></div>
</section>
<%@ include file="../fragments/footer.jspf" %>
