<%@ include file="../fragments/tags.jspf" %>
<%@ include file="../fragments/header.jspf" %>
<section class="card"><h2><c:out value="${amendment.number}"/> <span class="badge"><c:out value="${amendment.status}"/></span></h2>
  <dl><dt>対象受注</dt><dd><a href="<c:out value='${ctx}'/>/orders.do?op=detail&amp;id=<c:out value='${amendment.order.id}'/>"><c:out value="${amendment.order.number}"/></a> · <c:out value="${amendment.order.customerName}"/></dd><dt>申請基準 / 現在受注の更新番号</dt><dd><c:out value="${amendment.baseOrderVersion}"/> / <c:out value="${amendment.order.version}"/></dd><dt>元納期 → 提案納期</dt><dd><fmt:formatDate value="${amendment.originalRequestedDate}" pattern="yyyy-MM-dd"/> → <fmt:formatDate value="${amendment.requestedDate}" pattern="yyyy-MM-dd"/></dd><dt>税込金額（元 / 提案）</dt><dd><fmt:formatNumber value="${amendment.originalTotalAmount}" pattern="#,##0.00"/> / <fmt:formatNumber value="${amendment.proposedTotalAmount}" pattern="#,##0.00"/> 円</dd><dt>受注残の与信影響差</dt><dd><fmt:formatNumber value="${amendment.exposureDelta}" pattern="#,##0.00"/> 円</dd><dt>変更理由</dt><dd class="prewrap"><c:out value="${amendment.reason}"/></dd><dt>申請者 / 日時</dt><dd><c:out value="${amendment.requestedBy}"/> / <fmt:formatDate value="${amendment.requestedAt}" pattern="yyyy-MM-dd HH:mm"/></dd><dt>処理者 / 日時</dt><dd><c:out value="${amendment.decidedBy}"/> / <fmt:formatDate value="${amendment.decidedAt}" pattern="yyyy-MM-dd HH:mm"/></dd><dt>処理理由 / 適用後受注更新番号</dt><dd><c:out value="${amendment.decisionReason}"/> / <c:out value="${amendment.appliedOrderVersion}"/></dd></dl>
  <c:if test="${amendment.status eq 'REQUESTED' and amendment.baseOrderVersion ne amendment.order.version}"><p class="notice">受注の更新番号が申請時から変わっています。申請を取り消し、最新の受注から再申請してください。</p></c:if>
</section>
<section class="card"><h2>数量変更と申請時の明細写し</h2><div class="table-wrap"><table><thead><tr><th>受注明細 / 商品</th><th class="number">元総数 → 提案総数</th><th class="number">元引当 / 出荷済 / 取消済</th><th>入数</th><th class="number">保存済み単価 / 税率</th></tr></thead><tbody><c:forEach items="${amendment.lines}" var="line"><tr><td><c:out value="${line.orderLine.lineNumber}"/> · <c:out value="${line.orderLine.productCode}"/> <c:out value="${line.orderLine.productName}"/></td><td class="number"><c:out value="${line.originalQuantity}"/> → <c:out value="${line.targetQuantity}"/></td><td class="number"><c:out value="${line.originalAllocatedQuantity}"/> / <c:out value="${line.originalShippedQuantity}"/> / <c:out value="${line.originalCancelledQuantity}"/></td><td><c:out value="${line.packSize}"/></td><td class="number"><fmt:formatNumber value="${line.unitPrice}" pattern="#,##0.00"/> / <fmt:formatNumber value="${line.taxRate}" type="percent"/></td></tr></c:forEach><c:if test="${empty amendment.lines}"><tr><td colspan="5" class="empty">数量変更はありません。納期のみの変更申請です。</td></tr></c:if></tbody></table></div></section>
<c:if test="${amendment.status eq 'REQUESTED'}">
  <section class="card"><h2>承認前の確認</h2><p class="help">全受注・明細の基準スナップショットが一致する場合のみ承認できます。変更後も出荷済み・取消済み数量、価格・税率は保持されます。途中で状態が変わった申請は自動で基準を更新しません。</p>
    <c:if test="${not empty openInstructions}"><div class="notice"><strong>未確定の出荷指示があります。倉庫担当者が明示的に取り消してください。</strong><ul><c:forEach items="${openInstructions}" var="shipment"><li><a href="<c:out value='${ctx}'/>/shipments.do?op=detail&amp;id=<c:out value='${shipment.id}'/>"><c:out value="${shipment.number}"/></a></li></c:forEach></ul></div></c:if>
    <form action="<c:out value='${ctx}'/>/orderAmendments.do" method="post"><%@ include file="../fragments/identity.jspf" %><label>却下・取消理由<textarea name="reason" maxlength="500"><c:out value="${form.reason}"/></textarea></label>
      <div class="actions"><c:if test="${canMANAGER}"><c:if test="${amendment.requestedById ne actor.userId and empty openInstructions}"><button name="op" value="approve" class="primary">承認して一括適用</button></c:if><button name="op" value="reject">却下</button></c:if><c:if test="${canMANAGER or (canSALES and amendment.requestedById eq actor.userId)}"><button name="op" value="cancel" class="danger">申請取消</button></c:if></div>
    </form>
  </section>
</c:if>
<div class="actions"><a class="button" href="<c:out value='${ctx}'/>/orderAmendments.do">一覧へ</a><a class="button" href="<c:out value='${ctx}'/>/orders.do?op=detail&amp;id=<c:out value='${amendment.order.id}'/>">受注へ</a></div>
<%@ include file="../fragments/footer.jspf" %>
