<%@ include file="../fragments/tags.jspf" %>
<%@ include file="../fragments/header.jspf" %>
<section class="card"><h2>請求書 <c:out value="${invoice.number}"/> <span class="badge"><c:out value="${invoice.status}"/></span></h2>
  <div class="grid"><dl><dt>請求先</dt><dd><c:out value="${invoice.customerName}"/> 御中</dd><dt>請求先住所</dt><dd><c:out value="${invoice.postalCode}"/> <c:out value="${invoice.billingAddress}"/></dd><dt>対象期間</dt><dd><fmt:formatDate value="${invoice.periodStart}" pattern="yyyy-MM-dd"/> ～ <fmt:formatDate value="${invoice.periodEnd}" pattern="yyyy-MM-dd"/></dd><dt>発行日 / 支払期日</dt><dd><fmt:formatDate value="${invoice.issuedDate}" pattern="yyyy-MM-dd"/> / <fmt:formatDate value="${invoice.dueDate}" pattern="yyyy-MM-dd"/></dd></dl>
    <dl><dt>税抜 / 消費税</dt><dd class="number"><fmt:formatNumber value="${invoice.netAmount}" pattern="#,##0.00"/> / <fmt:formatNumber value="${invoice.taxAmount}" pattern="#,##0.00"/></dd><dt>請求合計</dt><dd class="number"><strong><fmt:formatNumber value="${invoice.totalAmount}" pattern="#,##0.00"/> 円</strong></dd><dt>消込済 / クレジット</dt><dd class="number"><fmt:formatNumber value="${invoice.paidAmount}" pattern="#,##0.00"/> / <fmt:formatNumber value="${invoice.creditedAmount}" pattern="#,##0.00"/></dd><dt>請求残高</dt><dd class="number"><fmt:formatNumber value="${invoice.outstandingAmount}" pattern="#,##0.00"/> 円</dd></dl>
  </div>
</section>
<section class="card"><h2>請求明細</h2><div class="table-wrap"><table><thead><tr><th>行 / 内容</th><th>元出荷</th><th class="number">数量</th><th class="number">単価</th><th>税率</th><th class="number">税抜金額</th></tr></thead><tbody>
  <c:forEach items="${invoice.lines}" var="line"><tr><td><c:out value="${line.lineNumber}"/> · <c:out value="${line.description}"/></td><td><a href="<c:out value='${ctx}'/>/shipments.do?op=detail&amp;id=<c:out value='${line.shipmentLine.shipment.id}'/>"><c:out value="${line.shipmentLine.shipment.number}"/></a></td><td class="number"><c:out value="${line.quantity}"/></td><td class="number"><fmt:formatNumber value="${line.unitPrice}" pattern="#,##0.00"/></td><td><fmt:formatNumber value="${line.taxRate}" type="percent"/></td><td class="number"><fmt:formatNumber value="${line.netAmount}" pattern="#,##0.00"/></td></tr></c:forEach>
</tbody></table></div></section>
<section class="card"><h2>請求操作・監査情報</h2><dl><dt>作成者</dt><dd><c:out value="${invoice.createdBy}"/> / <fmt:formatDate value="${invoice.createdAt}" pattern="yyyy-MM-dd HH:mm"/></dd><dt>確定者</dt><dd><c:out value="${invoice.finalizedBy}"/> / <fmt:formatDate value="${invoice.finalizedAt}" pattern="yyyy-MM-dd HH:mm"/></dd><dt>取消理由</dt><dd><c:out value="${invoice.cancellationReason}"/></dd></dl>
  <c:if test="${invoice.status eq 'DRAFT' and (canBILLING or canBATCH)}"><form action="<c:out value='${ctx}'/>/invoices.do" method="post"><%@ include file="../fragments/identity.jspf" %><label>下書き取消理由<textarea name="reason" maxlength="1000"><c:out value="${form.reason}"/></textarea></label><div class="actions"><button name="op" value="finalize" class="primary">請求を確定</button><c:if test="${canBILLING}"><button name="op" value="cancel" class="danger">下書き取消</button></c:if></div></form></c:if>
  <div class="actions"><a class="button" href="<c:out value='${ctx}'/>/invoices.do">一覧へ</a><c:if test="${canBILLING or canMANAGER}"><a class="button" href="<c:out value='${ctx}'/>/invoices.do?op=credits&amp;customerId=<c:out value='${invoice.customer.id}'/>">返品クレジット</a><a class="button" href="<c:out value='${ctx}'/>/payments.do?customerId=<c:out value='${invoice.customer.id}'/>">この得意先の入金</a></c:if></div>
</section>
<%@ include file="../fragments/footer.jspf" %>
