<%@ include file="../fragments/tags.jspf" %>
<%@ include file="../fragments/header.jspf" %>
<section class="card"><h2><c:out value="${apPayment.number}"/> <span class="badge"><c:out value="${apPayment.status}"/></span></h2>
  <dl><dt>仕入先</dt><dd><c:out value="${apPayment.supplierName}"/></dd><dt>支払日 / 方法</dt><dd><fmt:formatDate value="${apPayment.paymentDate}" pattern="yyyy-MM-dd"/> / <c:out value="${apPayment.method}"/></dd><dt>支払額</dt><dd><fmt:formatNumber value="${apPayment.amount}" pattern="#,##0.00"/> 円</dd><dt>振込照合番号</dt><dd><c:out value="${apPayment.reference}"/></dd><dt>備考</dt><dd class="prewrap"><c:out value="${apPayment.notes}"/></dd><dt>計上者 / 日時</dt><dd><c:out value="${apPayment.createdBy}"/> / <fmt:formatDate value="${apPayment.createdAt}" pattern="yyyy-MM-dd HH:mm"/></dd><dt>取消日 / 担当 / 理由</dt><dd><fmt:formatDate value="${apPayment.cancellationDate}" pattern="yyyy-MM-dd"/> / <c:out value="${apPayment.cancelledBy}"/> / <c:out value="${apPayment.cancellationReason}"/></dd><dt>受付キー</dt><dd class="mono"><c:out value="${apPayment.requestKey}"/></dd></dl>
</section>
<section class="card"><h2>消込明細</h2><div class="table-wrap"><table><thead><tr><th>請求管理番号 / 仕入先請求番号</th><th class="number">消込額</th><th>状態 / 取消日</th></tr></thead><tbody><c:forEach items="${apPayment.lines}" var="line"><tr><td><a href="<c:out value='${ctx}'/>/apInvoices.do?op=detail&amp;id=<c:out value='${line.invoice.id}'/>"><c:out value="${line.invoice.number}"/></a><br><c:out value="${line.invoice.supplierInvoiceNumber}"/></td><td class="number"><fmt:formatNumber value="${line.amount}" pattern="#,##0.00"/></td><td><c:out value="${line.status}"/><br><fmt:formatDate value="${line.reversalDate}" pattern="yyyy-MM-dd"/></td></tr></c:forEach></tbody></table></div></section>
<c:if test="${canBILLING and apPayment.status eq 'POSTED'}"><section class="card"><h2>支払全体の取消</h2><p class="help">全消込を一括取消し、対象請求の未払残高を戻します。個別明細だけの取消ではありません。</p><form action="<c:out value='${ctx}'/>/apPayments.do" method="post"><%@ include file="../fragments/identity.jspf" %><input type="hidden" name="op" value="cancel"><label>取消理由<textarea name="reason" maxlength="500" required><c:out value="${form.reason}"/></textarea></label><div class="actions"><button class="danger">支払と全消込を取消</button></div></form></section></c:if>
<div class="actions"><a class="button" href="<c:out value='${ctx}'/>/apPayments.do">一覧へ</a><a class="button" href="<c:out value='${ctx}'/>/apReports.do?op=statement&amp;supplierId=<c:out value='${apPayment.supplier.id}'/>">仕入先元帳</a></div>
<%@ include file="../fragments/footer.jspf" %>
