<%@ include file="../fragments/tags.jspf" %>
<%@ include file="../fragments/header.jspf" %>
<section class="card">
  <div class="actions"><a class="button" href="<c:out value='${ctx}'/>/apReports.do?op=open">未払・支払期日</a><a class="button" href="<c:out value='${ctx}'/>/apReports.do?op=receipts">未請求の検収入荷</a><a class="button" href="<c:out value='${ctx}'/>/apReports.do?op=variance">差異承認待ち</a><a class="button" href="<c:out value='${ctx}'/>/apReports.do?op=statement">仕入先元帳</a></div>
  <c:choose><c:when test="${reportMode eq 'open'}"><p class="help">基準日時点の支払・値引・取消を反映した未払残高です。開始日・終了日は支払期日で絞り込みます。</p></c:when><c:when test="${reportMode eq 'receipts'}"><p class="help">検収良品のうち、取消されていない仕入先請求にまだ照合されていない数量です。不良品は照合できません。期間条件は入荷日です。</p></c:when><c:when test="${reportMode eq 'variance'}"><p class="help">下書き請求の差異承認待ち一覧です。期間条件は仕入先請求日です。</p></c:when><c:otherwise><p class="help">仕入先を選択してください。請求計上・値引計上・支払・取消をそれぞれの発生日で表示します。期間合計・期末残高は検索期間全体、行の表示はページ単位です。</p></c:otherwise></c:choose>
  <%@ include file="../fragments/ap-search.jspf" %>
</section>
<c:if test="${not empty statement}"><section class="card"><h2><c:out value="${statement.supplier.name}"/> · 仕入先元帳</h2><dl><dt>期首残高</dt><dd><fmt:formatNumber value="${statement.openingBalance}" pattern="#,##0.00"/></dd><dt>当期増加 / 減少</dt><dd><fmt:formatNumber value="${statement.charges}" pattern="#,##0.00"/> / <fmt:formatNumber value="${statement.reductions}" pattern="#,##0.00"/></dd><dt>期末残高</dt><dd><strong><fmt:formatNumber value="${statement.closingBalance}" pattern="#,##0.00"/> 円</strong></dd></dl></section></c:if>
<section class="card"><div class="table-wrap"><table>
  <c:choose>
    <c:when test="${reportMode eq 'receipts'}"><thead><tr><th>入荷明細ID</th><th>入荷 / 発注番号</th><th>商品 / 入荷日</th><th class="number">良品 / 不良</th><th class="number">照合済 / 未照合</th><th class="number">検収単価</th></tr></thead><tbody>
      <c:forEach items="${results.items}" var="row"><tr><td class="mono">#<c:out value="${row.receiptLineId}"/></td><td><c:out value="${row.receiptNumber}"/><br><c:out value="${row.purchaseOrderNumber}"/></td><td><span class="mono">商品ID #<c:out value="${row.productId}"/></span><br><c:out value="${row.productCode}"/> <c:out value="${row.productName}"/><br><fmt:formatDate value="${row.receiptDate}" pattern="yyyy-MM-dd"/></td><td class="number"><c:out value="${row.acceptedQuantity}"/> / <c:out value="${row.rejectedQuantity}"/></td><td class="number"><c:out value="${row.matchedQuantity}"/> / <strong><c:out value="${row.availableQuantity}"/></strong></td><td class="number"><fmt:formatNumber value="${row.unitCost}" pattern="#,##0.00"/></td></tr></c:forEach>
    </tbody></c:when>
    <c:when test="${reportMode eq 'variance'}"><thead><tr><th>請求管理番号</th><th>仕入先</th><th>数量照合</th><th class="number">差異 / 絶対差異</th><th>起票 / 最終変更</th><th>支払期日</th></tr></thead><tbody>
      <c:forEach items="${results.items}" var="row"><tr><td><a href="<c:out value='${ctx}'/>/apInvoices.do?op=detail&amp;id=<c:out value='${row.id}'/>"><c:out value="${row.number}"/></a></td><td><c:out value="${row.supplierName}"/></td><td><c:out value="${row.fullyMatched ? '照合済' : '未照合あり'}"/></td><td class="number"><fmt:formatNumber value="${row.varianceAmount}" pattern="#,##0.00"/> / <fmt:formatNumber value="${row.absoluteVarianceAmount}" pattern="#,##0.00"/></td><td><c:out value="${row.createdBy}"/> / <c:out value="${row.lastChangedBy}"/></td><td><fmt:formatDate value="${row.dueDate}" pattern="yyyy-MM-dd"/></td></tr></c:forEach>
    </tbody></c:when>
    <c:when test="${reportMode eq 'statement'}"><thead><tr><th>日付 / 区分</th><th>伝票 / 参照番号</th><th class="number">増加</th><th class="number">減少</th><th class="number">残高</th></tr></thead><tbody>
      <c:forEach items="${results.items}" var="row"><c:choose><c:when test="${row.type eq 'INVOICE'}"><c:set var="documentRoute" value="/apInvoices.do"/></c:when><c:when test="${row.type eq 'CREDIT'}"><c:set var="documentRoute" value="/apCredits.do"/></c:when><c:otherwise><c:set var="documentRoute" value="/apPayments.do"/></c:otherwise></c:choose>
        <tr><td><fmt:formatDate value="${row.date}" pattern="yyyy-MM-dd"/><br><c:out value="${row.type}"/></td><td><a href="<c:out value='${ctx}${documentRoute}'/>?op=detail&amp;id=<c:out value='${row.documentId}'/>"><c:out value="${row.number}"/></a><br><c:out value="${row.reference}"/></td><td class="number"><fmt:formatNumber value="${row.charge}" pattern="#,##0.00"/></td><td class="number"><fmt:formatNumber value="${row.reduction}" pattern="#,##0.00"/></td><td class="number"><fmt:formatNumber value="${row.balance}" pattern="#,##0.00"/></td></tr>
      </c:forEach>
    </tbody></c:when>
    <c:otherwise><thead><tr><th>請求管理番号 / ID</th><th>仕入先 / 請求番号</th><th>支払期日 / 超過日数</th><th class="number">請求額</th><th class="number">支払 / 値引</th><th class="number">未払残高</th></tr></thead><tbody>
      <c:forEach items="${results.items}" var="row"><tr><td><a href="<c:out value='${ctx}'/>/apInvoices.do?op=detail&amp;id=<c:out value='${row.invoiceId}'/>"><c:out value="${row.number}"/></a><br><span class="mono">#<c:out value="${row.invoiceId}"/></span></td><td><c:out value="${row.supplierName}"/><br><c:out value="${row.supplierInvoiceNumber}"/></td><td><fmt:formatDate value="${row.dueDate}" pattern="yyyy-MM-dd"/> / <c:out value="${row.daysOverdue}"/>日</td><td class="number"><fmt:formatNumber value="${row.totalAmount}" pattern="#,##0.00"/></td><td class="number"><fmt:formatNumber value="${row.paidAmount}" pattern="#,##0.00"/> / <fmt:formatNumber value="${row.creditedAmount}" pattern="#,##0.00"/></td><td class="number"><strong><fmt:formatNumber value="${row.outstandingAmount}" pattern="#,##0.00"/></strong></td></tr></c:forEach>
    </tbody></c:otherwise>
  </c:choose>
</table></div><c:if test="${empty results.items}"><p class="empty">対象データはありません。仕入先元帳の場合は仕入先も指定してください。</p></c:if><%@ include file="../fragments/pagination.jspf" %></section>
<%@ include file="../fragments/footer.jspf" %>
